name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codeberg-medium-lazy
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - run: sudo groupadd nixbld || true
      - run: for i in $(seq 1 10); do sudo useradd -M -G nixbld nixbld$i || true; done

      - name: Install Nix
        uses: https://github.com/nixbuild/nix-quick-install-action@v34
      
      - name: Setup environment
        uses: https://github.com/nicknovitski/nix-develop@v1

      - name: Build site
        run: dx bundle --out-dir dist --release

      - name: Deploy site
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist/public --project-name apb-color-converter --branch production
